'use client';

import { useState } from 'react';
import Background from '../components/Background';
import GlassHeart from '../components/GlassHeart';
import PasswordBox from '../components/PasswordBox';
import CinematicPreloader from '../components/CinematicPreloader';

export default function Home() {
  const [preloaderComplete, setPreloaderComplete] =
      useState(false);

        return (
            <main className="relative min-h-screen overflow-hidden bg-[#020202] text-white">
                  {!preloaderComplete && (
                          <CinematicPreloader
                                    onComplete={() => {
                                                setPreloaderComplete(true);
                                                          }}
                                                                  />
                                                                        )}

                                                                              <Background />

                                                                                    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_32%,rgba(214,175,85,0.12),transparent_32%)]" />

                                                                                          <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/10 via-black/45 to-black" />

                                                                                                <div className="pointer-events-none absolute inset-x-0 top-0 h-48 bg-gradient-to-b from-black via-black/70 to-transparent" />

                                                                                                      <div className="pointer-events-none absolute inset-x-0 bottom-0 h-56 bg-gradient-to-t from-black via-black/80 to-transparent" />

                                                                                                            <div className="pointer-events-none absolute inset-4 rounded-[32px] border border-white/[0.06] sm:inset-6 md:inset-8" />

                                                                                                                  <div className="pointer-events-none absolute left-1/2 top-0 h-28 w-px -translate-x-1/2 bg-gradient-to-b from-yellow-200/50 to-transparent" />

                                                                                                                        <section
                                                                                                                                className={`
                                                                                                                                          relative
                                                                                                                                                    z-10
                                                                                                                                                              flex
                                                                                                                                                                        min-h-screen
                                                                                                                                                                                  min-h-[100svh]
                                                                                                                                                                                            items-center
                                                                                                                                                                                                      justify-center
                                                                                                                                                                                                                px-6
                                                                                                                                                                                                                          py-16
                                                                                                                                                                                                                                    transition-all
                                                                                                                                                                                                                                              duration-[1400ms]
                                                                                                                                                                                                                                                        sm:px-8
                                                                                                                                                                                                                                                                  ${
                                                                                                                                                                                                                                                                              preloaderComplete
                                                                                                                                                                                                                                                                                            ? 'scale-100 opacity-100 blur-0'
                                                                                                                                                                                                                                                                                                          : 'scale-105 opacity-0 blur-md'
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                            `}
                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                          <div className="mx-auto flex w-full max-w-5xl flex-col items-center text-center">
                                                                                                                                                                                                                                                                                                                                                    <div className="fade-up mb-8 flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                <span className="h-px w-10 bg-gradient-to-r from-transparent to-yellow-200/40" />

                                                                                                                                                                                                                                                                                                                                                                            <p className="text-[9px] uppercase tracking-[0.75em] text-yellow-200/65 sm:text-[10px]">
                                                                                                                                                                                                                                                                                                                                                                                          Private Experience
                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="h-px w-10 bg-gradient-to-l from-transparent to-yellow-200/40" />
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="fade-up fade-up-delay-1 relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="pointer-events-none absolute left-1/2 top-1/2 h-56 w-56 -translate-x-1/2 -translate-y-1/2 rounded-full bg-yellow-200/[0.06] blur-[90px]" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                              <GlassHeart />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="fade-up fade-up-delay-2 mt-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mb-5 text-[9px] uppercase tracking-[0.6em] text-white/25 sm:text-[10px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            One Story. One Person.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1 className="luxury-title max-w-4xl text-5xl leading-[0.95] tracking-[-0.04em] text-white sm:text-6xl md:text-8xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Before You
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="gold-text italic">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Continue...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="fade-up fade-up-delay-3 mx-auto mt-10 flex w-full max-w-xs items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="h-px flex-1 bg-gradient-to-r from-transparent to-yellow-200/35" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="font-serif text-lg text-yellow-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ☾
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="h-px flex-1 bg-gradient-to-l from-transparent to-yellow-200/35" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="fade-up fade-up-delay-3 mt-9 max-w-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="font-serif text-lg font-light leading-8 text-white/45 sm:text-xl sm:leading-9">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        This story was never written for everyone.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-3 font-serif text-xl italic leading-8 text-yellow-100/85 sm:text-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              It belongs to only one person.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="fade-up fade-up-delay-4 mt-12 w-full max-w-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <PasswordBox />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="fade-up fade-up-delay-4 mt-10 flex flex-col items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-[8px] uppercase tracking-[0.55em] text-white/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Protected Memory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="mt-4 h-8 w-px bg-gradient-to-b from-yellow-200/35 to-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="pointer-events-none absolute left-8 top-8 hidden text-[8px] uppercase tracking-[0.5em] text-white/15 md:block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Our Story
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="pointer-events-none absolute right-8 top-8 hidden text-[8px] uppercase tracking-[0.5em] text-white/15 md:block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          01 / 10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }